### ISSUE TITLE
Revise Structure to Add "Getting Started"

### ISSUE THREAD

**Issue by dsklavos** [tenstorrent/tenstorrent.github.io#22]
In the navigation sidebar:

1. Please remove the "SUPPORT" header.
2. Add a "GETTING STARTED" header to the top of the list.

This should be the structure under that header:

- Hardware Setup
- Software Setup
- First 5 Things to Do
- Support

3. Create placeholder .MD files for each one; Milan and I will build them out once they exist.

**Comment by dimitri-tenstorrent** [comment]
As per conversation with Milan, 
- Update home page to new quick start guide that Milan built.
- Remove Software and Utilities section as it is captured in the new guide
- Change the https://docs.tenstorrent.com/tt-metalium/latest/get_started/get_started.html#quick-start-guide - Milan will update
- Remove Installation sections - https://docs.tenstorrent.com/tt-metalium/latest/installing.html and https://docs.tenstorrent.com/ttnn/latest/ttnn/installing.html

**Comment by dimitri-tenstorrent** [comment]
Additionally,

- For Get started section of tt-metalium and tt-nn, change the links to point to Github original .md files.
- Remove 
```Installation and environment setup instructions are in the GitHub repository front-page README: https://github.com/tenstorrent/tt-metal/blob/main/INSTALLING.md```
- Also in TTNN Get started remove `Installation and environment setup instructions are in the [installation guide](https://docs.tenstorrent.com/ttnn/latest/ttnn/installing.html).`

**Comment by dimitri-tenstorrent** [comment]
For TT-Buda,

- Remove TT-Buda installation section - https://docs.tenstorrent.com/pybuda/latest/installation.html
- Under User Guide, remove Quick Start section - https://docs.tenstorrent.com/pybuda/latest/user_guide.html#quick-start

**Comment by milank94** [comment]
Edit line 2 in <https://docs.tenstorrent.com/pybuda/latest/index.html#introduction-to-pybuda to say>:

```bash
For a quick start, follow [First 5 Things](https://github.com/tenstorrent/tt-buda-demos/tree/main/first_5_steps) for **TT-Buda**.
```

**Comment by milank94** [comment]
[quickstart.md](https://github.com/user-attachments/files/17752038/quickstart.md)

Make this the new homepage

**Comment by dimitri-tenstorrent** [comment]
![Image](https://github.com/user-attachments/assets/319cd688-8d4a-4545-b643-4ee0cb0f996f)
![Image](https://github.com/user-attachments/assets/6f5952dd-909a-41f6-9fe9-1c80e8b8a2d6)
![Image](https://github.com/user-attachments/assets/20b3f6ee-a3b7-430e-99f4-d508696a110e)

**Comment by milank94** [comment]
@dimitri-tenstorrent found a few more places that reference the old software install instructions that should be removed and replaced with a link to the getting started guide:

- https://docs.tenstorrent.com/aibs/grayskull/installation.html#software-setup
- https://docs.tenstorrent.com/aibs/wormhole/installation.html#software-setup
- https://docs.tenstorrent.com/systems/quietbox/specifications.html#software-setup
- https://docs.tenstorrent.com/systems/quietbox/support.html
- https://docs.tenstorrent.com/systems/t3000/specifications.html#software-setup
- https://docs.tenstorrent.com/systems/t3000/support.html#tenstorrent-support
- https://docs.tenstorrent.com/systems/t1000/specifications.html#software-setup
- https://docs.tenstorrent.com/systems/t1000/support.html#tenstorrent-support
- https://docs.tenstorrent.com/systems/t7000/specifications.html#software-setup
- https://docs.tenstorrent.com/systems/t7000/support.html

**Comment by dimitri-tenstorrent** [comment]
@milank94 Could we put this in another issue please and I will close this one?

**Comment by milank94** [comment]
> [@milank94](https://github.com/milank94) Could we put this in another issue please and I will close this one?

Yes - here you go: https://github.com/tenstorrent/tenstorrent.github.io/issues/24
