### ISSUE TITLE
"Getting Started" page in TT-NN contains link to unformatted installation guide

### ISSUE THREAD

**Issue by bgoelTT** [tenstorrent/tenstorrent.github.io#26]
Reproduction steps:
1. navigate to the [TT-NN homepage](https://docs.tenstorrent.com/ttnn/latest/index.html)
2. Click on the "Getting Started" heading to navigate to the getting started page (should arrive at https://docs.tenstorrent.com/ttnn/latest/ttnn/get_started.html)
3. Click on the hyperlinked "installation guide" text

You should now be faced with the unformatted installation guide

**Comment by dimitri-tenstorrent** [comment]
Fixed in 9c536f233182c361dc0eb7c0a3f810289c13be99
