### ISSUE TITLE
Hitting several broken links on the docs site, specifically for metal: 

### ISSUE THREAD

**Issue by milank94** [tenstorrent/tenstorrent.github.io#8]
Hitting several broken links on the docs site, specifically for metal: https://docs.tenstorrent.com/ttnn/latest/ttnn/get_started.html#install-and-build
If I try to select “installation guide”, “Falcon 7B demo folder”, “TT-NN simple module” — all leads to 404 errors.

**Comment by Shubhamsaboo** [comment]
These links are also broken @dimitri-tenstorrent 

1. https://docs.tenstorrent.com/tt-metalium/latest/get_started/get_started.html#install-and-build
2. https://docs.tenstorrent.com/tt-metalium/latest/get_started/get_started.html#where-to-go-from-here

**Comment by dimitri-tenstorrent** [comment]
Guys, we will need the Metal team to update this file and convert it into `.rst` format. 
https://github.com/tenstorrent/tt-metal/blob/main/docs/source/ttnn/ttnn/installing.md
It is currently in `.md` while every other file is in `.rst`. I am not sure of the history but I ll ask if Raymond Kim knows.

**Comment by Shubhamsaboo** [comment]
On this page https://docs.tenstorrent.com/ttnn/latest/ttnn/get_started.html Falcon-7B demo folder link is broken. 

It should point to: https://github.com/tenstorrent/tt-metal/tree/main/models/demos/ttnn_falcon7b
